name: Docker Build, Test & Deploy to Azure App Service (Linux)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        cd backend
        dotnet restore

    - name: Run tests
      run: |
        cd backend/Tests/uniPoint_backend_tests
        dotnet test

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: f3c3ce74-b6e3-4832-a4a4-9bca4d6f7886
        tenant-id: 03789cef-0dbf-4ae9-bd93-cfcf6abae60f
        client-secret: b6i8Q~jD1FNsQsOThr.U7IQpX_.OlBOCcg.Egbiu
        subscription-id: ec2a3399-e799-45db-84d2-3cef09d60387

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest ./backend
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest

    - name: Deploy to Azure App Service (Linux)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest

# AZURE_CLIENT_ID: f3c3ce74-b6e3-4832-a4a4-9bca4d6f7886
# AZURE_TENANT_ID: 03789cef-0dbf-4ae9-bd93-cfcf6abae60f
# AZURE_CLIENT_SECRET: b6i8Q~jD1FNsQsOThr.U7IQpX_.OlBOCcg.Egbiu
# AZURE_SUBSCRIPTION_ID: ec2a3399-e799-45db-84d2-3cef09d60387
# secret:
#       - value: b6i8Q~jD1FNsQsOThr.U7IQpX_.OlBOCcg.Egbiu
#       - id: 9a5d2601-c19c-42bd-b75a-75b481691520
