name: Docker Build, Test & Deploy to Azure App Service (Linux)

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        cd backend
        dotnet restore

    - name: Run tests
      run: |
        cd backend/Tests/uniPoint_backend_tests
        dotnet test

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest ./backend
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest

    - name: Deploy to Azure App Service (Linux)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/unipoint-backend:latest
